DEFAULT_ADMIN_ACCOUNT="admin"
DEFAULT_ADMIN_PASSWORD=`openssl rand -base64 45`
JWT_SECRET=`openssl rand -base64 45`
SALT=`openssl rand -base64 15`

cat > .env <<EOF
DEFAULT_ADMIN_ACCOUNT=$DEFAULT_ADMIN_ACCOUNT
DEFAULT_ADMIN_PASSWORD=$DEFAULT_ADMIN_PASSWORD
JWT_SECRET=$JWT_SECRET
SALT=$SALT
EOF